server {
  listen 80;
  server_name www.nutripripereira.com;

  return 301 http://nutripripereira.com$request_uri;
}

server {
  listen 80;
  server_name nutripripereira.com;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /50x.html {
    internal;
  }
}
